[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[phases.build]
cmds = ["pnpm install --frozen-lockfile=false && pnpm --filter @workspace/api-server run build"]

[start]
cmd = "pnpm --filter @workspace/api-server run start"